<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Reduced real time physics simulation library slice for Helengine box and sphere integration.</Description>
    <Configurations>Debug;Release;ReleaseNoProfiling</Configurations>
    <PackageTags>physics;3d;rigid body;real time;simulation</PackageTags>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
    <NoWarn>1573;1591;CA2014</NoWarn>
  </PropertyGroup>

  <Import Project="..\CommonSettings.props" />

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;DEBUG;CHECKMATH;PROFILE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;RELEASE;PROFILE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='ReleaseNoProfiling'">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BepuUtilities\BepuUtilities.Minimal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DefaultTypes.cs" />
    <Compile Remove="Minimal\**\*.cs" />
    <Compile Remove="CollisionDetection\SweepTasks\**\*.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\*Capsule*.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\*ConvexHull*.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\*Cylinder*.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\CapsuleTriangleTester.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\TriangleConvexHullTester.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\TriangleCylinderTester.cs" />
    <Compile Remove="CollisionDetection\CollisionTasks\TrianglePairTester.cs" />
    <Compile Remove="Constraints\AreaConstraint.cs" />
    <Compile Remove="Constraints\Angular*.cs" />
    <Compile Remove="Constraints\BallSocket*.cs" />
    <Compile Remove="Constraints\CenterDistance*.cs" />
    <Compile Remove="Constraints\Distance*.cs" />
    <Compile Remove="Constraints\Hinge.cs" />
    <Compile Remove="Constraints\LinearAxis*.cs" />
    <Compile Remove="Constraints\OneBodyAngular*.cs" />
    <Compile Remove="Constraints\OneBodyLinear*.cs" />
    <Compile Remove="Constraints\PointOnLineServo.cs" />
    <Compile Remove="Constraints\SwivelHinge.cs" />
    <Compile Remove="Constraints\Twist*.cs" />
    <Compile Remove="Constraints\VolumeConstraint.cs" />
    <Compile Remove="Constraints\Weld.cs" />
    <Compile Remove="Trees\Tree_Diagnostics.cs" />
    <Compile Include="Minimal\DefaultTypes.Minimal.cs" Link="DefaultTypes.cs" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CollisionDetection\DepthRefiner.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DepthRefiner.tt</DependentUpon>
    </Compile>
    <Compile Update="Constraints\Contact\ContactConvexTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContactConvexTypes.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="CollisionDetection\DepthRefiner.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>DepthRefiner.cs</LastGenOutput>
    </None>
    <None Update="Constraints\Contact\ContactConvexTypes.tt">
      <LastGenOutput>ContactConvexTypes.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>
</Project>
